# Generated by Django 5.0.3 on 2024-03-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='logo',
            field=models.ImageField(null=True, upload_to='tracks/logos/'),
        ),
    ]
